name: Publish node.js Package
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
      - run: npx nx run-many -t build --all --exclude storybook-composition docs
      - run: npx nx run-many -t nx-release-publish --all --skip-nx-cache --exclude storybook-composition docs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
